global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: null
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: gitlab
    static_configs:
      - targets:
          - gitlab:80
    metrics_path: /-/metrics

  - job_name: sonarqube
    static_configs:
      - targets:
          - sonarqube:9000
    metrics_path: /api/monitoring/metrics

  - job_name: nexus
    static_configs:
      - targets:
          - nexus:8081
    metrics_path: /service/metrics/prometheus

  - job_name: jenkins
    static_configs:
      - targets:
          - jenkins:8080
    metrics_path: /prometheus

  - job_name: docker
    static_configs:
      - targets:
          - host.docker.internal:9323