---
# Homepage configuration
title: "DevOps Dashboard"
subtitle: "Development & CI/CD Services"
# logo: "logo.png"  # Commented out until we add custom logo
icon: "fas fa-server"

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> for DevOps Team</p>'

columns: "3"
connectivityCheck: true

theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

message:
  style: "is-dark"
  title: "DevOps Environment"
  icon: "fa fa-grin"
  content: "Welcome to your complete CI/CD development environment. All services are running and ready for development."

links:
  - name: "Documentation"
    icon: "fab fa-github"
    url: "https://github.com/your-org/devops-docs"
    target: "_blank"
  - name: "Issue Tracker"
    icon: "fas fa-bug"
    url: "https://github.com/your-org/issues"
    target: "_blank"

services:
  - name: "System Health"
    icon: "fas fa-heartbeat"
    items:
      - name: "GitLab"
        icon: "fab fa-gitlab"
        subtitle: "Git Repository & CI/CD"
        tag: "core"
        type: "Ping"
        endpoint: "http://gitlab:80/-/health"
        url: "http://192.168.1.187:8090"
        target: "_blank"
      - name: "SonarQube"
        icon: "fas fa-search"
        subtitle: "Code Quality Analysis"
        tag: "core"
        type: "Ping"
        endpoint: "http://sonarqube:9000/api/system/status"
        url: "http://192.168.1.187:9000"
        target: "_blank"
      - name: "Nexus"
        icon: "fas fa-archive"
        subtitle: "Artifact Repository"
        tag: "core"
        type: "Ping"
        endpoint: "http://nexus:8081/service/rest/v1/status"
        url: "http://192.168.1.187:8081"
        target: "_blank"
      - name: "Jenkins"
        icon: "fab fa-jenkins"
        subtitle: "Build Automation"
        tag: "automation"
        type: "Ping"
        endpoint: "http://jenkins:8080/login"
        url: "http://192.168.1.187:8084"
        target: "_blank"
      - name: "Grafana"
        icon: "fas fa-chart-line"
        subtitle: "Monitoring Dashboard"
        tag: "monitoring"
        type: "Ping"
        endpoint: "http://grafana:3000/api/health"
        url: "http://192.168.1.187:3000"
        target: "_blank"
      - name: "Traefik"
        icon: "fas fa-route"
        subtitle: "Reverse Proxy"
        tag: "infrastructure"
        type: "Ping"
        endpoint: "http://traefik:8080/ping"
        url: "http://192.168.1.187:8083"
        target: "_blank"

  - name: "Version Control"
    icon: "fas fa-code-branch"
    items:
      - name: "GitLab"
        icon: "fab fa-gitlab"
        subtitle: "Git Repository & CI/CD"
        tag: "app"
        keywords: "git repository cicd pipeline"
        url: "http://192.168.1.187:8090"
        target: "_blank"
      - name: "GitLab Runner"
        icon: "fas fa-running"
        subtitle: "CI/CD Runner"
        tag: "service"
        keywords: "runner cicd"
        url: "http://192.168.1.187:8090/admin/runners"
        target: "_blank"

  - name: "Code Quality & Security"
    icon: "fas fa-shield-alt"
    items:
      - name: "SonarQube"
        icon: "fas fa-search"
        subtitle: "Code Quality Analysis"
        tag: "app"
        keywords: "code quality static analysis"
        url: "http://192.168.1.187:9000"
        target: "_blank"
      - name: "OWASP ZAP"
        icon: "fas fa-shield-alt"
        subtitle: "Security Testing"
        tag: "security"
        keywords: "security testing vulnerability"
        url: "http://192.168.1.187:8093"
        target: "_blank"

  - name: "Artifact Management"
    icon: "fas fa-box"
    items:
      - name: "Nexus Repository"
        icon: "fas fa-archive"
        subtitle: "Artifact & Package Repository"
        tag: "app"
        keywords: "artifacts packages maven npm"
        url: "http://192.168.1.187:8081"
        target: "_blank"
      - name: "MinIO Storage"
        icon: "fas fa-cloud"
        subtitle: "S3-Compatible Object Storage"
        tag: "storage"
        keywords: "storage s3 objects files"
        url: "http://192.168.1.187:9002"
        target: "_blank"

  - name: "CI/CD & Automation"
    icon: "fas fa-cogs"
    items:
      - name: "Jenkins"
        icon: "fab fa-jenkins"
        subtitle: "Build Automation Server"
        tag: "app"
        keywords: "jenkins build automation cicd"
        url: "http://192.168.1.187:8084"
        target: "_blank"
      - name: "Webhook Receiver"
        icon: "fas fa-webhook"
        subtitle: "Webhook Handler"
        tag: "service"
        keywords: "webhooks api automation"
        url: "http://192.168.1.187:9900"
        target: "_blank"

  - name: "Monitoring & Observability"
    icon: "fas fa-chart-line"
    items:
      - name: "Grafana"
        icon: "fas fa-chart-line"
        subtitle: "Metrics & Dashboards"
        tag: "monitoring"
        keywords: "monitoring dashboard metrics visualization"
        url: "http://192.168.1.187:3000"
        target: "_blank"
      - name: "Prometheus"
        icon: "fas fa-fire"
        subtitle: "Metrics Collection"
        tag: "monitoring"
        keywords: "prometheus metrics monitoring"
        url: "http://192.168.1.187:9091"
        target: "_blank"

  - name: "Infrastructure Management"
    icon: "fas fa-server"
    items:
      - name: "Portainer"
        icon: "fab fa-docker"
        subtitle: "Docker Management"
        tag: "infrastructure"
        keywords: "docker containers management"
        url: "https://192.168.1.187:9443"
        target: "_blank"
      - name: "Traefik"
        icon: "fas fa-route"
        subtitle: "Reverse Proxy & Load Balancer"
        tag: "infrastructure"
        keywords: "proxy loadbalancer routing"
        url: "http://192.168.1.187:8083"
        target: "_blank"
      - name: "Vault"
        icon: "fas fa-lock"
        subtitle: "Secrets Management"
        tag: "security"
        keywords: "secrets vault security"
        url: "http://192.168.1.187:8200"
        target: "_blank"

  - name: "Cache & Data"
    icon: "fas fa-database"
    items:
      - name: "Redis"
        icon: "fas fa-memory"
        subtitle: "In-Memory Cache"
        tag: "database"
        keywords: "redis cache memory database"
        url: "#"
        target: "_blank"
      - name: "PostgreSQL"
        icon: "fas fa-database"
        subtitle: "Database (SonarQube)"
        tag: "database"
        keywords: "postgresql database sql"
        url: "#"
        target: "_blank"