# java-spring-boot CI/CD Pipeline Example
stages:
  - build
  - test
  - quality
  - deploy

variables:
  DOCKER_REGISTRY: "localhost:5050"

build_java-spring-boot:
  stage: build
  script:
    - echo "Building java-spring-boot application"
    # Add build commands specific to java-spring-boot

test_java-spring-boot:
  stage: test
  script:
    - echo "Testing java-spring-boot application"
    # Add test commands specific to java-spring-boot

quality_check:
  stage: quality
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner
  only:
    - main
    - develop

deploy_java-spring-boot:
  stage: deploy
  script:
    - echo "Deploying java-spring-boot application"
    # Add deployment commands
  only:
    - main
